apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: open-telemetry-poc
build:
  insecureRegistries:
    - 172.30.1.92
    - 70.30.174.97
    - registry.insecure.io:5000
  artifacts:
    - image: app-a
      jib:
        project: app-a
    - image: app-b
      jib:
        project: app-b
    - image: app-c
      jib:
        project: app-c
manifests:
  rawYaml:
    - raw-yaml/ingress/*.yaml
    - raw-yaml/grafana-family/grafana.yaml
    - raw-yaml/grafana-family/lokiManifest.yaml
    - raw-yaml/otel/*
    - raw-yaml/demo-apps/*.yaml

deploy:
  helm:
    releases:
      - name: jaeger
        repo: https://jaegertracing.github.io/helm-charts
        remoteChart: jaeger
        version: 0.71.14
        setValues:
          provisionDataStore.cassandra: false
          provisionDataStore.elasticsearch: false
          provisionDataStore.kafka: false
          allInOne.enabled: true
          ingester.enabled: false
          agent.enabled: false
          collector.enabled: false
          query.enabled: false
      - name: tempo
        repo: https://grafana.github.io/helm-charts
        remoteChart: tempo-distributed
        namespace: tempo
        version: 1.6.1
        createNamespace: true
        setValues:
          traces.otlp.grpc.enabled: true
#      - name: loki
#        repo: https://grafana.github.io/helm-charts
#        remoteChart: loki
#        setValues:
#          minio.enabled: true
#          loki.commonConfig.replication_factor: 1
#          singleBinary.replicas: 1

# helm install --values ./helmValuesFiles/lokiValues-minio.yaml loki grafana/loki


#helm -n tempo-test install tempo grafana/tempo-distributed -f custom.yaml

#deploy:
#  kubectl:
#    mani

#portForward:
#  - resourceType: deployment
#    resourceName: ingress-nginx-controller
#    namespace: ingress-nginx
#    port: 8080
#    localPort: 80
