apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: open-telemetry-poc
build:
  insecureRegistries:
    - 172.30.1.92
    - 70.30.174.97
    - registry.insecure.io:5000
  artifacts:
    - image: app-a
      jib:
        project: app-a
    - image: app-b
      jib:
        project: app-b
    - image: app-c
      jib:
        project: app-c
manifests:
  rawYaml:
    - raw-yaml/ingress/*.yaml
#    - raw-yaml/jaeger/jaeger-operator.yaml
#    - raw-yaml/jaeger/jaeger.yaml
#    - raw-yaml/grafana-family/*
    - raw-yaml/otel/*
    - raw-yaml/demo-apps/*.yaml

deploy:
  helm:
    releases:
      - name: jaeger
        repo: https://jaegertracing.github.io/helm-charts
        remoteChart: jaeger
        version: 0.71.14
        setValues:
          provisionDataStore.cassandra: false
          provisionDataStore.elasticsearch: false
          provisionDataStore.kafka: false
          allInOne.enabled: true
          ingester.enabled: false
          agent.enabled: false
          collector.enabled: false
          query.enabled: false

#deploy:
#  kubectl:
#    mani

#portForward:
#  - resourceType: deployment
#    resourceName: ingress-nginx-controller
#    namespace: ingress-nginx
#    port: 8080
#    localPort: 80
