apiVersion: v1
kind: Service
metadata:
  name: app-a
  labels:
    app: app-a
spec:
  type: ClusterIP
  selector:
    app: app-a
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a
  labels:
    app: app-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-a
  template:
    metadata:
      labels:
        app: app-a
    spec:
      containers:
      - name: app-a
        image: app-a
        ports:
        - containerPort: 8080
        env:
        - name: spring.application.name
          value: app-a
        - name: server.port
          value: "8080"
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/usr/local/tomcat/lib/opentelemetry-javaagent.jar"
        - name: OTEL_JAVAAGENT_LOGGING
          value: application
        - name: OTEL_TRACES_EXPORTER
          value: logging
        - name: OTEL_METRICS_EXPORTER
          value: none
        - name: OTEL_LOGS_EXPORTER
          value: logging
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 400m
            memory: 400Mi
