# ref : https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/main/examples/k8s/otel-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  labels:
    app: opentelemetry
    component: otel-collector-config
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            endpoint: ${env:MY_POD_IP}:4318
    processors:
      resource:
        attributes:
          - action: insert
            key: loki.resource.labels
            value: service.name
      batch:
    exporters:
      otlp/jaeger:
        endpoint: "http://jaeger-collector:4317"
        tls:
          insecure: true
      otlp/tempo:
        endpoint: "http://tempo-distributor.tempo:4317"
        tls:
          insecure: true
      otlp/elastic:
        endpoint: "http://elasticsearch:9200"
        tls:
          insecure: true
      elasticsearch/trace:
        endpoints: [http://elasticsearch:9200]
        tls:
          insecure: true
        traces_index: trace_index
        flush:
          bytes: 5242880
          interval: 5
      elasticsearch/log:    
        endpoints: [http://elasticsearch:9200]
        tls:
          insecure: true
        logs_index: log_index
        flush:
          bytes: 5242880
          interval: 5
      file:
        path: ./test.log
      logging:
        verbosity: detailed
      loki:
        endpoint: http://loki-gateway:80/loki/api/v1/push
        default_labels_enabled:
          exporter: true
          job: true
          instance: true
          level: true
    service:
      pipelines:
        logs:
          receivers: [otlp]
          processors: [resource]
          exporters: [logging, loki, otlp/elastic]
        traces:
          receivers: [otlp]
          processors: [resource]
          exporters: [logging, otlp/tempo, otlp/jaeger, otlp/elastic]
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  ports:
    - name: otlp-grpc # Default endpoint for OpenTelemetry gRPC receiver.
      port: 4317
      protocol: TCP
      targetPort: 4317
    - name: otlp-http # Default endpoint for OpenTelemetry HTTP receiver.
      port: 4318
      protocol: TCP
      targetPort: 4318
    - name: metrics # Default endpoint for querying metrics.
      port: 8888
  selector:
    component: otel-collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  replicas: 1 #TODO - adjust this to your own requirements
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.84.0
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 200m
              memory: 200Mi
          volumeMounts:
            - mountPath: /var/log
              name: varlog
              readOnly: true
            - mountPath: /var/lib/docker/containers
              name: varlibdockercontainers
              readOnly: true
            - mountPath: /etc/otelcol-contrib/config.yaml
              name: data
              subPath: config.yaml
              readOnly: true
          ports:
            - containerPort: 55679 # Default endpoint for ZPages.
            - containerPort: 4317 # Default endpoint for OpenTelemetry receiver.
            - containerPort: 14250 # Default endpoint for Jaeger gRPC receiver.
            - containerPort: 14268 # Default endpoint for Jaeger HTTP receiver.
            - containerPort: 9411 # Default endpoint for Zipkin receiver.
            - containerPort: 8888  # Default endpoint for querying metrics.
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
      terminationGracePeriodSeconds: 0
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: data
          configMap:
            name: otel-collector-config

