apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  type: ClusterIP
  selector:
    app: elasticsearch
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:8.10.1
        ports:
        - containerPort: 9200
        env:
          - name: discovery.type
            value: "single-node"
          - name: xpack.security.enabled
            value: "false"
        resources:
          requests:
            cpu: 600m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 1Gi
