apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: elasticsearch:8.10.1
          env:
            - name: discovery.type
              value: "single-node"
          ports:
            - containerPort: 9200
          resources:
            requests:
              cpu: 600m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      name: kibana-port
      port: 9200
      targetPort: 9200
  type: LoadBalancer

---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch
  labels:
    license.k8s.elastic.co/type: enterprise_trial
  annotations:
    elastic.co/eula: accepted