apiVersion: v1
kind: Service
metadata:
  name: app-b
  labels:
    app: app-b
spec:
  type: ClusterIP
  selector:
    app: app-b
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-b
  labels:
    app: app-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-b
  template:
    metadata:
      labels:
        app: app-b
    spec:
      containers:
      - name: app-b
        image: app-b
        ports:
        - containerPort: 8080
        env:
        - name: spring.application.name
          value: app-b
        - name: server.port
          value: "8080"
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/usr/local/tomcat/webapps/ROOT/WEB-INF/lib/opentelemetry-javaagent.jar"
        - name: OTEL_JAVAAGENT_ENABLED
          value: "true"
        - name: OTEL_SDK_DISABLED
          value: "false"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "grpc"
        - name: OTEL_SERVICE_NAME
          value: "app-b"
        - name: OTEL_TRACES_EXPORTER
          value: otlp # otlp or none or logging
        - name: OTEL_LOGS_EXPORTER
          value: otlp # otlp or none or logging
        - name: OTEL_METRICS_EXPORTER
          value: none # otlp or none or logging
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector:4317"
        - name: OTEL_JAVAAGENT_LOGGING
          value: application
        resources:
          requests:
            cpu: 600m
            memory: 600Mi
          limits:
            cpu: 600m
            memory: 600Mi
